spring:
  application:
    name: pass-batch
  datasource:
    url: jdbc:mysql://localhost:3306/batch_local
#    ?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: woojoo
    password: 0425
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # Spring Boot2부터 default DBCP는 hikariCP입니다.
      maximum-pool-size: 20 # pool에 보관 가능한 최대 connection 수

  batch:
#    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행합니다. 임베디드인 경우에는 기본적으로 실행하는데, always 설정을 하면 임베디드 타입처럼 항상 활성화시킬 수 있습니다.
      # 초기 수행한 이후에는 꺼두어도 됩니다.
#      initialize-schema: always
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none